"""Declarative base shared by every service's SQLAlchemy models.

A single naming convention keeps autogenerated Alembic migrations
consistent (constraint names, index names) across services.
"""

from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # Every service in this codebase works in timezone-aware UTC datetimes
    # (see e.g. ingestion/vision/events all using datetime.now(UTC)) --
    # without this, `Mapped[datetime]` defaults to a naive TIMESTAMP
    # column, silently dropping tzinfo on write and returning naive
    # datetimes on read, which then break comparisons against the
    # timezone-aware datetimes the rest of the code always uses.
    type_annotation_map = {datetime: DateTime(timezone=True)}


class TimestampMixin:
    """`created_at`/`updated_at` columns, populated by Postgres itself.

    `server_default` so even Core-style inserts (e.g. `INSERT ... ON
    CONFLICT DO UPDATE`, which bypass ORM attribute defaults) still get a
    value without the application supplying one. `onupdate` covers the
    ORM-driven update path (set an attribute, then flush/commit) -- but a
    raw Core UPDATE or ON CONFLICT DO UPDATE statement bypasses `onupdate`
    too, so those must set `updated_at = func.now()` explicitly in their
    SET clause.
    """

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())
