"""initial schema

Revision ID: 66ab99299a05
Revises:
Create Date: 2026-07-04 22:42:44.548021

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "66ab99299a05"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=1024), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_warehouse_id"), "alerts", ["warehouse_id"], unique=False)
    op.create_index(
        "ix_alerts_warehouse_status", "alerts", ["warehouse_id", "status"], unique=False
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rtsp_url", sa.String(length=2048), nullable=False),
        sa.Column("zone", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cameras")),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("bbox_x_min", sa.Float(), nullable=False),
        sa.Column("bbox_y_min", sa.Float(), nullable=False),
        sa.Column("bbox_x_max", sa.Float(), nullable=False),
        sa.Column("bbox_y_max", sa.Float(), nullable=False),
        sa.Column("velocity_vx", sa.Float(), nullable=True),
        sa.Column("velocity_vy", sa.Float(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("camera_id", "track_id", name=op.f("uq_entities_camera_id")),
    )
    op.create_index(op.f("ix_entities_camera_id"), "entities", ["camera_id"], unique=False)
    op.create_index(op.f("ix_entities_last_seen_at"), "entities", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_entities_warehouse_id"), "entities", ["warehouse_id"], unique=False)
    op.create_index(
        "ix_entities_warehouse_last_seen",
        "entities",
        ["warehouse_id", "last_seen_at"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("camera_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.String(length=1024), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("zone_id", sa.Uuid(), nullable=True),
        sa.Column("zone_name", sa.String(length=255), nullable=True),
        sa.Column("dwell_time_seconds", sa.Float(), nullable=True),
        sa.Column("related_track_id", sa.Integer(), nullable=True),
        sa.Column("related_label", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_camera_id"), "events", ["camera_id"], unique=False)
    op.create_index(op.f("ix_events_occurred_at"), "events", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_events_warehouse_id"), "events", ["warehouse_id"], unique=False)
    op.create_table(
        "zone_occupancy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("zone_name", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_zone_occupancy_entity_id_entities")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_occupancy")),
    )
    op.create_index(
        op.f("ix_zone_occupancy_entity_id"), "zone_occupancy", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_zone_occupancy_exited_at"), "zone_occupancy", ["exited_at"], unique=False
    )
    op.create_index(
        op.f("ix_zone_occupancy_warehouse_id"), "zone_occupancy", ["warehouse_id"], unique=False
    )
    op.create_index(
        "ix_zone_occupancy_warehouse_zone_exited",
        "zone_occupancy",
        ["warehouse_id", "zone_id", "exited_at"],
        unique=False,
    )
    op.create_index(op.f("ix_zone_occupancy_zone_id"), "zone_occupancy", ["zone_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zone_occupancy_zone_id"), table_name="zone_occupancy")
    op.drop_index("ix_zone_occupancy_warehouse_zone_exited", table_name="zone_occupancy")
    op.drop_index(op.f("ix_zone_occupancy_warehouse_id"), table_name="zone_occupancy")
    op.drop_index(op.f("ix_zone_occupancy_exited_at"), table_name="zone_occupancy")
    op.drop_index(op.f("ix_zone_occupancy_entity_id"), table_name="zone_occupancy")
    op.drop_table("zone_occupancy")
    op.drop_index(op.f("ix_events_warehouse_id"), table_name="events")
    op.drop_index(op.f("ix_events_occurred_at"), table_name="events")
    op.drop_index(op.f("ix_events_camera_id"), table_name="events")
    op.drop_table("events")
    op.drop_index("ix_entities_warehouse_last_seen", table_name="entities")
    op.drop_index(op.f("ix_entities_warehouse_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_last_seen_at"), table_name="entities")
    op.drop_index(op.f("ix_entities_camera_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("cameras")
    op.drop_index("ix_alerts_warehouse_status", table_name="alerts")
    op.drop_index(op.f("ix_alerts_warehouse_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
